import { SignInButton, SignOutButton, useUser } from '@clerk/nextjs'
import { type NextPage } from 'next'
import Head from 'next/head'

import { api } from '../utils/api'

const Home: NextPage = () => {
  const user = useUser()
  const { data } = api.posts.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Twi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <header>
          <h1 className="text-4xl font-bold text-white">Twi</h1>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </header>
        <section>
          {data?.map((post) => (
            <div key={post.id}>
              <p>{post.content}</p>
            </div>
          ))}
        </section>
      </main>
    </>
  )
}

export default Home
