import { SignInButton, SignOutButton, useUser } from '@clerk/nextjs'
import { type NextPage } from 'next'
import Head from 'next/head'

import { api } from '../utils/api'
import PostWiz from '~/components/PostWiz'
import PostView from '~/components/PostView'

const Home: NextPage = () => {
  const user = useUser()
  const { data, isLoading } = api.posts.getAll.useQuery()

  if (isLoading) return <section>Loading...</section>

  if (!data) return <section>Something went wrong</section>

  return (
    <>
      <Head>
        <title>Twi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <section className="w-full border-x border-slate-400 md:max-w-2xl">
          <header className="flex justify-between border-b border-slate-400 p-4">
            <h1 className="text-4xl font-bold text-white self-center">Twi</h1>
            <div className="flex justify-center items-center gap-2 w-8/12">
              {user.isSignedIn && <PostWiz />}
            </div>
            <div className="flex self-center">
              {!user.isSignedIn && <SignInButton />}
              {!!user.isSignedIn && <SignOutButton />}
            </div>
          </header>
          <section>
            {data?.map(({ post, author }) => (
              <PostView key={post.id} post={post} author={author} />
            ))}
          </section>
        </section>
      </main>
    </>
  )
}

export default Home
