import { SignInButton, SignOutButton, useUser } from '@clerk/nextjs'
import { type NextPage } from 'next'
import Head from 'next/head'

import { api } from '../utils/api'
import PostWiz from '~/components/PostWiz'
import { FaCrow } from 'react-icons/fa'
import Feed from '~/components/Feed'

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser()

  api.posts.getAll.useQuery()

  if (!userLoaded) return <div />

  return (
    <>
      <Head>
        <title>Crowie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <section className="w-full border-x border-slate-400 md:max-w-2xl">
          <header className="flex justify-between border-b border-slate-400 p-4">
            <h1 className="text-4xl font-bold text-white self-center">
              <FaCrow className="ml-6 text-5xl" />
            </h1>
            <div className="flex justify-center items-center gap-2 w-8/12">
              {isSignedIn && <PostWiz />}
            </div>
            <div className="flex self-center">
              {!isSignedIn && <SignInButton />}
              {!!isSignedIn && <SignOutButton />}
            </div>
          </header>
          <Feed />
        </section>
      </main>
    </>
  )
}

export default Home
